-- MySQL Script generated by MySQL Workbench
-- Mon Dec 12 13:42:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema workout_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workout_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workout_db` DEFAULT CHARACTER SET utf8 ;
USE `workout_db` ;

-- -----------------------------------------------------
-- Table `workout_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workout_db`.`user` (
  `id` VARCHAR(12) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workout_db`.`today`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workout_db`.`today` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `user_id` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_today_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_today_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `workout_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workout_db`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workout_db`.`exercise` (
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workout_db`.`one_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workout_db`.`one_set` (
  `id` INT NOT NULL,
  `number_of_repetitions` INT NOT NULL,
  `today_id` INT NOT NULL,
  `exercise_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_one_set_today1_idx` (`today_id` ASC) VISIBLE,
  INDEX `fk_one_set_exercise1_idx` (`exercise_name` ASC) VISIBLE,
  CONSTRAINT `fk_one_set_today1`
    FOREIGN KEY (`today_id`)
    REFERENCES `workout_db`.`today` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_one_set_exercise1`
    FOREIGN KEY (`exercise_name`)
    REFERENCES `workout_db`.`exercise` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workout_db`.`done`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workout_db`.`done` (
  `id` INT NOT NULL,
  `numbers_of_repetitions` INT NOT NULL,
  `today_id` INT NOT NULL,
  `exercise_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_done_today1_idx` (`today_id` ASC) VISIBLE,
  INDEX `fk_done_exercise1_idx` (`exercise_name` ASC) VISIBLE,
  CONSTRAINT `fk_done_today1`
    FOREIGN KEY (`today_id`)
    REFERENCES `workout_db`.`today` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_done_exercise1`
    FOREIGN KEY (`exercise_name`)
    REFERENCES `workout_db`.`exercise` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workout_db`.`need`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workout_db`.`need` (
  `id` INT NOT NULL,
  `numbers_of_repetitions` INT NOT NULL,
  `today_id` INT NOT NULL,
  `exercise_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_need_to_do_today1_idx` (`today_id` ASC) VISIBLE,
  INDEX `fk_need_exercise1_idx` (`exercise_name` ASC) VISIBLE,
  CONSTRAINT `fk_need_to_do_today1`
    FOREIGN KEY (`today_id`)
    REFERENCES `workout_db`.`today` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_need_exercise1`
    FOREIGN KEY (`exercise_name`)
    REFERENCES `workout_db`.`exercise` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workout_db`.`record_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workout_db`.`record_type` (
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workout_db`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workout_db`.`record` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `numbers_of_repetitions` INT NOT NULL,
  `user_id` VARCHAR(12) NOT NULL,
  `record_type_name` VARCHAR(100) NOT NULL,
  `exercise_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_record_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_record_record_type1_idx` (`record_type_name` ASC) VISIBLE,
  INDEX `fk_record_exercise1_idx` (`exercise_name` ASC) VISIBLE,
  CONSTRAINT `fk_record_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `workout_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_record_type1`
    FOREIGN KEY (`record_type_name`)
    REFERENCES `workout_db`.`record_type` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_exercise1`
    FOREIGN KEY (`exercise_name`)
    REFERENCES `workout_db`.`exercise` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
